In [1]:
import torch
import numpy as np

In [2]:
a = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]

In [3]:
A = torch.tensor(a)

In [4]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
A.ndimension()

2

In [6]:
A.shape

torch.Size([3, 4])

In [8]:
A.size()

torch.Size([3, 4])

In [9]:
A.numel()

12

In [10]:
A[0, 0]

tensor(0)

In [11]:
A[0][0]

tensor(0)

In [12]:
A[1:3, 2 ]

tensor([ 6, 10])

In [13]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]])

In [14]:
X + Y

tensor([[3, 1],
        [1, 3]])

In [15]:
2 * Y

tensor([[4, 2],
        [2, 4]])

In [16]:
X * Y

tensor([[2, 0],
        [0, 2]])

In [19]:
torch.matmul(X, Y)

tensor([[2, 1],
        [1, 2]])